In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('exercise_dataset.csv')
df.drop(['Calories per kg'], axis = 1, inplace = True)
df

   Activity, Exercise or Sport (1 hour)  130 lb  155 lb  180 lb  205 lb
0   Cycling, <10 mph, leisure bicycling     236     281     327     372
1              Cycling, >20 mph, racing     944    1126    1308    1489
2           Cycling, 10-11.9 mph, light     354     422     490     558
3        Cycling, 12-13.9 mph, moderate     472     563     654     745
4        Cycling, 14-15.9 mph, vigorous     590     704     817     931
..                                  ...     ...     ...     ...     ...
82         Swimming leisurely, not laps     354     422     490     558
83                 Ice skating, < 9 mph     325     387     449     512
84           Ice skating, average speed     413     493     572     651
85                 Ice skating, rapidly     531     633     735     838
86                     General cleaning     207     246     286     326

[87 rows x 5 columns]

In [3]:
df['CPK'] = 1
for i in range(0, len(df)):
    df['CPK'][i] = (df['130 lb'][i] / 59.1 + df['155 lb'][i] / 70.45 + df['180 lb'][i] / 81.81 + df['205 lb'][i] / 93.18) / 4
df

C:\Users\Bhavik\AppData\Local\Temp/ipykernel_2208/3801902956.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['CPK'][i] = (df['130 lb'][i] / 59.1 + df['155 lb'][i] / 70.45 + df['180 lb'][i] / 81.81 + df['205 lb'][i] / 93.18) / 4

   Activity, Exercise or Sport (1 hour)  130 lb  155 lb  180 lb  205 lb  CPK
0   Cycling, <10 mph, leisure bicycling     236     281     327     372    3
1              Cycling, >20 mph, racing     944    1126    1308    1489   15
2           Cycling, 10-11.9 mph, light     354     422     490     558    5
3        Cycling, 12-13.9 mph, moderate     472     563     654     745    7
4        Cycling, 14-15.9 mph, vigorous     590     704     817     931    9
..                                  ...     ...     ...     ...     ...  ...
82         Swimming leisurely, not laps     354     422     490     558    5
83                 Ice skating, < 9 mph     325     387     449     512    5
84           Ice skating, average speed     413     493     572     651    6
85                 Ice skating, rapidly     531     633     735     838    8
86                     General cleaning     207     246     286     326    3

[87 rows x 6 columns]

In [4]:
calories = 200
time = [0.5, 0.75, 1] #30 mins, 45 mins, 1hr
w = 70
l = []
for i in range(0, len(df)):
    cpk = df['CPK'][i] * w
    for t in time:
        if cpk * t <= 220 and cpk * t >= 180:
            l.append((df['Activity, Exercise or Sport (1 hour)'][i], t, cpk * t))
l

[('Cycling, <10 mph, leisure bicycling', 1, 210),
 ('Stationary cycling, moderate', 0.5, 210.0),
 ('Rowing machine, light', 1, 210),
 ('Rowing machine, moderate', 0.5, 210.0),
 ('Ballet, twist, jazz, tap', 0.75, 210.0),
 ('Badminton', 0.75, 210.0),
 ('Cricket (batting, bowling)', 0.75, 210.0),
 ('Golf, walking and carrying clubs', 0.75, 210.0),
 ('Gymnastics', 1, 210),
 ('Skateboarding', 0.75, 210.0),
 ('Roller skating', 0.5, 210.0),
 ('Table tennis, ping pong', 1, 210),
 ('Playing tennis', 0.5, 210.0),
 ('Walking 3.0 mph, moderate', 1, 210),
 ('Walking 3.5 mph, brisk pace', 1, 210),
 ('Walking 4.0 mph, very brisk', 0.75, 210.0),
 ('Walking 4.5 mph', 0.5, 210.0),
 ('Canoeing, rowing, moderate', 0.5, 210.0),
 ('Skin diving, scuba diving', 0.5, 210.0),
 ('Swimming laps, freestyle, slow', 0.5, 210.0),
 ('Ice skating, average speed', 0.5, 210.0),
 ('General cleaning', 1, 210)]

In [75]:
import random
import math
import statistics

In [85]:
init_centroids = [df.iloc[random.randint(0,86)], df.iloc[random.randint(0,86)], df.iloc[random.randint(0,86)]]
clust1_cent = init_centroids[0]
clust2_cent = init_centroids[1]
clust3_cent = init_centroids[2]
clust1_cent_CPK = clust1_cent.CPK
clust2_cent_CPK = clust2_cent.CPK
clust3_cent_CPK = clust3_cent.CPK

In [92]:
f = lambda x: x['CPK']
for i in range(0,100):
    clust1 = []
    clust2 = []
    clust3 = []
    for i in range(0,df.shape[0]):
        x = y = z = 0
        x = math.sqrt(( df['CPK'][i] - clust1_cent_CPK)**2)
        y = math.sqrt(( df['CPK'][i] - clust2_cent_CPK)**2)
        z = math.sqrt(( df['CPK'][i] - clust3_cent_CPK)**2)
        # print("X: {}, Y: {}, Z:{}".format(x,y,z))
        if x < y and x < z:
            clust1.append(df.iloc[i])
            # print("IF")
            # print(i)
        elif y < x and y < z:
            clust2.append(df.iloc[i])
            # print("ELIF")
            # print(i)
        else:
            clust3.append(df.iloc[i])
            # print("ELSE")
            # print(i)
        # print(i)
    clust1_CPK = [f(x) for x in clust1]
    clust2_CPK = [f(x) for x in clust2]
    clust3_CPK = [f(x) for x in clust3]
    clust1_cent_CPK = statistics.mean(clust1_CPK)
    clust2_cent_CPK = statistics.mean(clust2_CPK)
    clust3_cent_CPK = statistics.mean(clust3_CPK)
# clust1_CPK = [f(x) for x in clust1]
# clust2_CPK = [f(x) for x in clust2]
# clust3_CPK = [f(x) for x in clust3]
# clust1_cent_CPK = statistics.mean(clust1_CPK)
# clust2_cent_CPK = statistics.mean(clust2_CPK)
# clust3_cent_CPK = statistics.mean(clust3_CPK)

In [106]:
print(max(clust1_CPK),min(clust1_CPK))
print(max(clust2_CPK),min(clust2_CPK))
print(max(clust3_CPK),min(clust3_CPK))

17 10
8 6
9 1

In [110]:
clust1[0]

Activity, Exercise or Sport (1 hour)    Cycling, >20 mph, racing
130 lb                                                       944
155 lb                                                      1126
180 lb                                                      1308
205 lb                                                      1489
CPK                                                           15
Name: 1, dtype: object

In [ ]:
calories = 200
time = [0.5, 0.75, 1] #30 mins, 45 mins, 1hr
w = 70
l = []
for i in range(0, len(df)):
    cpk = df['CPK'][i] * w
    for t in time:
        if cpk * t <= 220 and cpk * t >= 180:
            l.append((df['Activity, Exercise or Sport (1 hour)'][i], t, cpk * t))